name: 'Health Check'
description: 'Checks the health of a deployed service'

inputs:
  url:
    description: 'URL to check'
    required: true
  max-attempts:
    description: 'Maximum number of attempts'
    required: false
    default: '24'
  retry-delay:
    description: 'Delay between retries'
    required: false
    default: '5s'
  discord-webhook:
    description: 'Discord webhook for failure notifications'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@e7d5ebdc9027fbf494d2d034f3e8fc78f8b7a2b9 # v5
      with:
        url: ${{ inputs.url }}
        max-attempts: ${{ inputs.max-attempts }}
        retry-delay: ${{ inputs.retry-delay }}
        retry-all: true

    - name: Notify on failure
      uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
      if: ${{ failure() && inputs.discord-webhook != '' }}
      with:
        webhook: ${{ inputs.discord-webhook }}
        url: ${{ inputs.url }}
